---
title: "Short Git startup tutorials in pdf format made with Rmarkdown"
author: "Sadi"
date: "24-1-2022"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=T}
# for pdf knitting, latex is required: change comment in code if absent
# install.packages('tinytex')
# tinytex::install_tinytex() 
knitr::opts_chunk$set(echo = TRUE)
```

These notes are just to practice the use of version control, RStudio and markdown
They stem from the Coursera course: 'The Data Scientist's Toolbox' 
and the Help pages on the Github website.



## Configure Git for use with Github

type in the command prompt 

git config --global user.name <"username">  
git config --global user.email <user-email>
(same email address you signed up for GitHub with)

confirm your changes by typing 

git config --list. 

If you notice any problems or want to change these values, 
just retype the original config commands from earlier with your desired changes
exit the command line by typing 

exit (and hit enter) 


## How to link RStudio with Github

In RStudio go to tools - global options - git/SVN,

check if Git.exe path is correct
Now, to link RStudio to GitHub,  

click "Create RSA Key" and when there is complete, click "Close".
Following this, in the first window again, click "View public key" 
and copy the string of numbers and letters. 
Close this window. 

You have now created a key that is specific to you 
which we will provide to GitHub so that it knows who you are 
when you commit a change from within RStudio.

Go to your account settings in Github
go to SSH and GPG keys and click "New SSH key". 
Paste the public key you have copied from RStudio into the key box 
and give it a title related to RStudio.
Confirm the addition of the key with your GitHub password

GitHub and RStudio are now linked.


## How to link a repository to Github

create/fork/clone a repository in Github

New repo: Name your new repository and give it a short description 
Click "Create Repository", 
copy the URL for your new repository 

In RStudio, select New Project, select Version Control, 
select Git as your version control software 
Paste in the repository URL from before, 
select the location where you would like the project stored 
When done, click on "Create Project"

Doing so will initialize a new project linked to the GitHub repository 
and open a new session of RStudio

Create a new R script 
Save the file

in the Git tab of the environment quadrant, you can see the new file  

Click the checkbox under Staged to stage your file
Click on it 

A new window should open that lists all of the changed files from earlier 
and below that shows the differences in the stage files from previous versions 
In the upper quadrant, in the message box, write a commit message. 
Click Commit and close the window

push your changes to the GitHub repository, 
go to your GitHub repository and see that the commit has been recorded


## How to get version control for an existing project

Open Git Bash or Terminal and navigate to the directory 
containing your project files. 
Move around directories by 

type
CD for change directory, followed by the path of the directory.

When the command prompt in the line before $ says the correct location
of your project, you are in the correct location. 

type 
git init 
git add. (with .!) (/ git add <path to file> for partial adding)

This Initializes this directory as a Git repository 
and Stages / adds all of the files in the directory to your local repository.
To have a look at what is staged:

git status

Commit these changes to the Git repository using 

git commit -m "Initial Commit" 

At this point, we have an R project linked to Git version control. 
To link it to Github, 

go to github.com

Create a new repository with the same name
note: do not initialize the readme, gitignore or license. 

Once you've created this repository, 
there is an option to push an existing repository from the command line 
with instructions below containing code on how to do so.

In Git Bash or Terminal, copy and paste these lines of code 
After doing so, refresh your GitHub page 

you should now have access to the Git tab in the upper right quadrant

any added (saved) changes you can now push to github:

select (stage) your new/changed file under the Git tab (upper right) 
click commit , add comment, commit
finally, Push


